# Generated by Django 3.2.8 on 2022-01-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20220112_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='status',
            field=models.CharField(choices=[('1', 'undone'), ('2', 'doing'), ('3', 'done')], default='1', max_length=10),
        ),
    ]
