# Generated by Django 3.2.8 on 2022-01-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_rename_status_todomodel_status1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='status1',
            new_name='status',
        ),
    ]
